$functionName = "sec-ws-ProPayResponseFunction"
clear
echo Publishing function...
dotnet publish
echo Compressing function code...
7z a -r .\drop.zip .\publish\*
echo Uploading to Lambda...
aws lambda update-function-code --function-name $functionName --zip-file fileb://.\drop.zip --region eu-north-1 | Out-Null
echo Cleaning up...
rm drop.zip
echo Done.